stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "us-east-1"
  IMAGE_NAME: "simpletime-service"
  ECS_CLUSTER_NAME: "simpletime-cluster"
  ECS_SERVICE_NAME: "simpletime_service"

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install awscli
  - apk add --no-cache docker
  - echo "Logging into Amazon ECR..."
    aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
      docker build -t $IMAGE_NAME:latest ./app
    - echo "Tagging Docker image..."
      docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:latest
    - echo "Pushing Docker image to Amazon ECR..."
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Updating ECS Service..."
      aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
  only:
    - main
